DO_BOX_URL = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
PRIVATE_KEY_PATH = "./id_rsa"
TOKEN = "*"

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  config.puppet_install.puppet_version = '6.24.0'
  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "./manifests"
    puppet.module_path = './modules'
  end

  config.vm.provider :digital_ocean do |provider, override|
    override.ssh.private_key_path = PRIVATE_KEY_PATH
    override.vm.box = 'digital_ocean'
    override.vm.box_url = DO_BOX_URL
    override.nfs.functional = false
    override.vm.allowed_synced_folder_types = :rsync
    override.nfs.functional = false
    provider.token = TOKEN
    provider.image = 'ubuntu-18-04-x64'
    provider.region = 'nyc1'
    provider.size = 's-1vcpu-1gb'
    provider.setup = false
  end

  config.vm.provider :virtualbox do |provider, override|
    override.vm.box = 'virtual_box'
    override.vm.box = "bento/ubuntu-18.04"
  end

  config.vm.define "app" do |appDroplet|
    appDroplet.vm.hostname = "appserver"
    appDroplet.vm.provision :puppet do |app_puppet|
      app_puppet.environment_path = './environments'
      app_puppet.environment = 'app'
    end
  end

  config.vm.define "db" do |dbDroplet|
    dbDroplet.vm.hostname = "dbserver"
    dbDroplet.vm.provision :puppet do |db_puppet|
      db_puppet.environment_path = './environments'
      db_puppet.environment = 'db'
    end
  end

end
